### ISSUE TITLE
User Stories 

### ISSUE THREAD

**Issue by adena6** [nuyem/Software-Engineering#1]
As a user, I want to I want to view a list of all the countries in the world organised in by largest population to smallest so that I can understand global population distribution. This also goes for viewing the list of all the cities in the world organised from largest population to smallest. Also, as a user I would like to filter countries by continent and view them organised by largest population to smallest.

**Comment by adena6** [comment]
> As a user, I want to I want to view a list of all the countries in the world organised in by largest population to smallest so that I can understand global population distribution. This also goes for viewing the list of all the cities in the world organised from largest population to smallest. Also, as a user I would like to filter countries by continent and view them organized by largest population to smallest.

Having trouble adding the user stories onto github

**Comment by Moustafa-33** [comment]
> > As a user, I want to I want to view a list of all the countries in the world organised in by largest population to smallest so that I can understand global population distribution. This also goes for viewing the list of all the cities in the world organised from largest population to smallest. Also, as a user I would like to filter countries by continent and view them organized by largest population to smallest.
> 
> Having trouble adding the user stories onto github

Come to room 210 and we will sort out all the issues.

**Comment by adena6** [comment]
> > > As a user, I want to I want to view a list of all the countries in the world organised in by largest population to smallest so that I can understand global population distribution. This also goes for viewing the list of all the cities in the world organised from largest population to smallest. Also, as a user I would like to filter countries by continent and view them organized by largest population to smallest.
> > 
> > 
> > Having trouble adding the user stories onto github
> 
> Come to room 210 and we will sort out all the issues.

On my way!

**Comment by Moustafa-33** [comment]
what other issues do you have with the work?
